# Generated by Django 4.2.30 on 2026-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerrequest",
            name="practice_skill_level",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
