"""
Loads the curated skill list into SkillTaxonomy.
Safe to re-run — uses update_or_create on slug.

    docker compose exec django python manage.py load_curated_skills
"""
from django.core.management.base import BaseCommand
from skills.models import SkillTaxonomy

SKILLS = [
    # ── Agriculture & Food ───────────────────────────────────────────────────
    ("permaculture",            "Permaculture",             "Permakultur",                  "Permacultura",                  "Permaculture"),
    ("organic-farming",         "Organic Farming",          "Ökologischer Landbau",         "Agricultura Ecológica",         "Agriculture Biologique"),
    ("market-gardening",        "Market Gardening",         "Marktgärtnerei",               "Horticultura de Mercado",       "Maraîchage"),
    ("beekeeping",              "Beekeeping",               "Imkerei",                      "Apicultura",                    "Apiculture"),
    ("composting",              "Composting",               "Kompostierung",                "Compostaje",                    "Compostage"),
    ("seed-saving",             "Seed Saving",              "Saatgutgewinnung",             "Conservación de Semillas",      "Conservation des Semences"),
    ("animal-husbandry",        "Animal Husbandry",         "Tierhaltung",                  "Ganadería",                     "Élevage"),
    ("dairy-farming",           "Dairy Farming",            "Milchwirtschaft",              "Producción Láctea",             "Production Laitière"),
    ("pruning",                 "Pruning",                  "Baumschnitt",                  "Poda",                          "Taille"),
    ("grafting",                "Grafting",                 "Veredelung",                   "Injerto",                       "Greffage"),
    ("bread-baking",            "Bread Baking",             "Brotbacken",                   "Panificación",                  "Boulangerie"),
    ("cheesemaking",            "Cheesemaking",             "Käseherstellung",              "Elaboración de Queso",          "Fabrication de Fromage"),
    ("brewing",                 "Brewing",                  "Bierbrauen",                   "Elaboración de Cerveza",        "Brassage"),
    ("fermentation",            "Fermentation",             "Fermentierung",                "Fermentación",                  "Fermentation"),
    ("food-preservation",       "Food Preservation",        "Lebensmittelkonservierung",    "Conservación de Alimentos",     "Conservation Alimentaire"),
    ("foraging",                "Foraging",                 "Wildkräuterkunde",             "Recolección Silvestre",         "Cueillette Sauvage"),
    ("herbalism",               "Herbalism",                "Kräuterkunde",                 "Herboristería",                 "Herboristerie"),
    ("mushroom-cultivation",    "Mushroom Cultivation",     "Pilzzucht",                    "Cultivo de Setas",              "Culture de Champignons"),
    ("winemaking",              "Winemaking",               "Weinherstellung",              "Elaboración de Vino",           "Vinification"),
    ("orchard-management",      "Orchard Management",       "Obstbaumanbau",                "Gestión de Huertos",            "Gestion du Verger"),
    ("greenhouse-management",   "Greenhouse Management",    "Gewächshausbewirtschaftung",   "Gestión de Invernadero",        "Gestion de Serre"),
    ("aquaponics",              "Aquaponics",               "Aquaponik",                    "Acuaponía",                     "Aquaponie"),
    ("agroforestry",            "Agroforestry",             "Agroforstwirtschaft",          "Agroforestería",                "Agroforesterie"),
    ("food-forest-design",      "Food Forest Design",       "Waldgartengestaltung",         "Diseño de Bosques de Alimentos","Conception de Forêt Nourricière"),
    ("vermicomposting",         "Vermicomposting",          "Wurmkompostierung",            "Vermicompostaje",               "Lombricompostage"),
    ("weeding",                 "Weeding",                  "Unkraut jäten",                "Deshierbe",                     "Désherbage"),
    ("fruit-tree-pruning",      "Fruit Tree Pruning",       "Obstbaumschnitt",              "Poda de Árboles Frutales",      "Taille des Arbres Fruitiers"),
    ("tree-felling",            "Tree Felling",             "Holzfällen",                   "Tala de Árboles",               "Abattage d'Arbres"),
    ("arboriculture",           "Tree Care",                "Baumpflege",                   "Cuidado de Árboles",            "Soin des Arbres"),
    ("holistic-management",     "Holistic Management",      "Ganzheitliches Weidemanagement","Manejo Holístico",              "Gestion Holistique"),
    ("syntropic-farming",       "Syntropic Farming",        "Syntropische Landwirtschaft",  "Agricultura Sintrópica",        "Agriculture Syntropique"),
    ("vegan-cooking",           "Vegan Cooking",            "Veganes Kochen",               "Cocina Vegana",                 "Cuisine Végane"),
    ("self-sufficiency",        "Self-Sufficiency",         "Selbstversorgung",             "Autosuficiencia",               "Autosuffisance"),
    ("fermentation-techniques", "Fermentation Techniques",   "Fermentationstechniken",       "Técnicas de Fermentación",      "Techniques de Fermentation"),
    ("terra-preta",             "Terra Preta",              "Terra Preta",                  "Terra Preta",                   "Terra Preta"),
    ("bokashi",                 "Bokashi Composting",       "Bokashi-Kompostierung",        "Compostaje Bokashi",            "Compostage Bokashi"),
    ("irrigation-systems",      "Irrigation Systems",       "Bewässerungssysteme",          "Sistemas de Riego",             "Systèmes d'Irrigation"),
    ("soil-regeneration",       "Soil Regeneration",        "Bodenregeneration",            "Regeneración del Suelo",        "Régénération des Sols"),
    ("mulching",                "Mulching",                 "Mulchen",                      "Acolchado",                     "Paillage"),
    ("pasture-management",      "Pasture Management",       "Weidemanagement",              "Gestión de Pasturas",           "Gestion des Pâturages"),
    ("rotational-grazing",      "Rotational Grazing",       "Rotationsbeweidung",           "Pastoreo Rotativo",             "Pâturage Tournant"),
    ("chicken-keeping",         "Chicken Keeping",          "Hühnerhaltung",                "Cría de Gallinas",              "Élevage de Poules"),
    ("goat-keeping",            "Goat Keeping",             "Ziegenhaltung",                "Cría de Cabras",                "Élevage de Chèvres"),
    ("seedling-propagation",    "Seedling Propagation",     "Jungpflanzenanzucht",          "Producción de Plántulas",       "Production de Semis"),
    ("nursery-management",      "Plant Nursery Management", "Pflanzenschule",               "Gestión de Viveros",            "Gestion de Pépinière"),
    ("olive-oil-production",    "Olive Oil Production",     "Olivenölherstellung",          "Producción de Aceite de Oliva", "Production d'Huile d'Olive"),
    ("herb-drying",             "Herb Drying & Processing", "Kräutertrocknung",             "Secado de Hierbas",             "Séchage des Herbes"),
    ("community-kitchen",       "Community Kitchen",        "Gemeinschaftsküche",           "Cocina Comunitaria",            "Cuisine Communautaire"),
    ("wood-fired-cooking",      "Wood-Fired Cooking",       "Kochen mit Holzofen",          "Cocina con Horno de Leña",      "Cuisine au Feu de Bois"),
    ("forest-gardening",        "Forest Gardening",         "Waldgartenpflege",             "Jardinería Forestal",           "Jardinage Forestier"),
    ("dumpster-diving",         "Dumpster Diving",          "Containern",                   "Recogida de Comida (Contenedores)", "Récupération Alimentaire (Poubelles)"),
    ("no-dig-gardening",        "No-Dig Gardening",         "Grabefreies Gärtnern",         "Jardinería sin Labranza",       "Jardinage Sans Travail du Sol"),
    ("raised-bed-gardening",    "Raised Bed Gardening",     "Hochbeet-Gartenbau",           "Cultivo en Camas Elevadas",     "Culture sur Buttes"),
    ("vertical-gardening",      "Vertical Gardening",       "Vertikales Gärtnern",          "Jardinería Vertical",           "Jardinage Vertical"),
    ("hydroponics",             "Hydroponics",              "Hydroponik",                   "Hidroponía",                    "Hydroponie"),
    ("aquaculture",             "Aquaculture",              "Aquakultur",                   "Acuicultura",                   "Aquaculture"),
    ("no-till-farming",         "No-Till Farming",          "Direktsaat",                   "Agricultura sin Labranza",      "Semis Direct"),
    ("cover-cropping",          "Cover Cropping",           "Zwischenfruchtanbau",          "Cultivos de Cobertura",         "Cultures de Couverture"),
    ("companion-planting",      "Companion Planting",       "Mischkultur",                  "Asociación de Cultivos",        "Plantes Compagnes"),
    ("succession-planting",     "Succession Planting",      "Staffelgärtnern",              "Siembra Escalonada",            "Plantation Échelonnée"),
    ("keyhole-gardening",       "Keyhole Gardening",        "Schlüssellochgarten",          "Jardín en Cerradura",           "Jardin en Trou de Serrure"),
    ("hugelkultur",             "Hügelkultur",              "Hügelbeet",                    "Cultivo en Camas Elevadas con Madera","Hügelkultur"),
    ("biointensive-gardening",  "Biointensive Gardening",   "Biointensiver Gartenbau",      "Agricultura Biointensiva",      "Jardinage Biointensif"),
    ("mulch-farming",           "Mulch Farming",            "Mulchsysteme",                 "Agricultura con Acolchado",     "Culture sous Paillage"),
    ("drip-irrigation-design",  "Drip Irrigation Design",   "Tropfbewässerungsplanung",     "Diseño de Riego por Goteo",     "Conception Goutte à Goutte"),
    ("seed-raising",            "Seed Raising",             "Jungpflanzenanzucht",          "Producción de Plántulas",       "Pépinière de Semis"),
    ("green-manure",            "Green Manure",             "Gründüngung",                  "Abono Verde",                   "Engrais Vert"),
    ("food-forest-layering",    "Food Forest Layering",     "Schichtenmodell Waldgarten",   "Estratificación de Bosque Comestible","Stratification Forêt Nourricière"),
    ("regenerative-grazing",    "Regenerative Grazing",     "Regenerative Beweidung",       "Pastoreo Regenerativo",         "Pâturage Régénératif"),

    # ── Construction & Building ──────────────────────────────────────────────
    ("carpentry",               "Carpentry",                "Zimmerei",                     "Carpintería",                   "Menuiserie"),
    ("masonry",                 "Masonry",                  "Maurerarbeiten",               "Albañilería",                   "Maçonnerie"),
    ("natural-building",        "Natural Building",         "Natürliches Bauen",            "Construcción Natural",          "Construction Naturelle"),
    ("straw-bale-construction", "Straw Bale Construction",  "Strohballenbau",               "Construcción con Balas de Paja","Construction en Bottes de Paille"),
    ("earthen-building",        "Earthen Building",         "Lehmbau",                      "Construcción con Tierra",       "Construction en Terre"),
    ("roofing",                 "Roofing",                  "Dachdeckerarbeiten",           "Techado",                       "Couverture"),
    ("plumbing",                "Plumbing",                 "Sanitärinstallation",          "Fontanería",                    "Plomberie"),
    ("electrical-installation", "Electrical Installation",  "Elektroinstallation",          "Instalación Eléctrica",         "Installation Électrique"),
    ("welding",                 "Welding",                  "Schweißen",                    "Soldadura",                     "Soudage"),
    ("woodworking",             "Woodworking",              "Holzbearbeitung",              "Trabajo en Madera",             "Travail du Bois"),
    ("blacksmithing",           "Blacksmithing",            "Schmiedehandwerk",             "Herrería",                      "Forge"),
    ("tiling",                  "Tiling",                   "Fliesenlegen",                 "Alicatado",                     "Carrelage"),
    ("plastering",              "Plastering",               "Verputzen",                    "Enlucido",                      "Plâtrage"),
    ("cob-building",            "Cob Building",             "Lehm-Stroh-Bauweise",          "Construcción con barro y paja", "Construction en terre et paille"),
    ("timber-framing",          "Timber Framing",           "Fachwerkbau",                  "Estructuras de Madera",         "Charpente Traditionnelle"),
    ("rocket-stove-building",   "Rocket Stove Building",    "Raketen Ofenbau",               "Construcción de Estufas Rocket","Construction de Poêle Dragon"),
    ("compost-toilet-building", "Compost Toilet Building",  "Komposttoilettenbau",          "Construcción de Baños Secos",   "Construction de Toilettes Sèches"),
    ("rammed-earth",            "Rammed Earth",             "Stampflehm",                   "Tierra Apisonada",              "Pisé"),
    ("earthen-plaster",         "Earthen Plaster",          "Lehmputz",                     "Revoque de Barro",              "Enduit de Terre"),
    ("adobe",                   "Adobe",                    "Adobe",                        "Adobe",                         "Adobe"),
    ("excavator-operation",     "Excavator Operation",      "Baggerfahren",                 "Manejo de Excavadoras",         "Conduite de Pelle"),
    ("crane-operation",         "Crane Operation",          "Kranbedienung",                "Manejo de Grúas",               "Conduite de Grue"),
    ("bricklaying",             "Bricklaying",              "Mauern",                       "Albañilería de Ladrillo",       "Pose de Briques"),
    ("tiny-house-building",     "Tiny House Building",      "Tiny-House-Bau",               "Construcción de Tiny Houses",   "Construction de Tiny Houses"),
    ("lime-plaster",            "Lime Plaster",             "Kalkputz",                     "Revoque de Cal",                "Enduit à la Chaux"),
    ("limewashing",             "Limewashing",              "Kalken",                       "Encalado",                      "Badigeon à la Chaux"),
    ("dry-stone-wall",          "Dry Stone Walling",        "Trockenmauerbau",              "Muros de Piedra Seca",          "Murs en Pierre Sèche"),
    ("earthbag-building",       "Earthbag Building",        "Erdbeutelbau",                 "Construcción con Sacos de Tierra","Construction en Sacs de Terre"),
    ("bamboo-construction",     "Bamboo Construction",      "Bambusbau",                    "Construcción con Bambú",        "Construction en Bambou"),
    ("window-installation",     "Window Installation",      "Fenstereinbau",                "Instalación de Ventanas",       "Pose de Fenêtres"),
    ("door-installation",       "Door Installation",        "Türeinbau",                    "Instalación de Puertas",        "Pose de Portes"),
    ("insulation",              "Natural Insulation",       "Natürliche Dämmung",           "Aislamiento Natural",           "Isolation Naturelle"),
    ("passive-solar-design",    "Passive Solar Design",     "Passiv-Solar-Design",          "Diseño Solar Pasivo",           "Conception Solaire Passive"),
    ("furniture-building",      "Furniture Building",       "Möbelbau",                     "Fabricación de Muebles",        "Fabrication de Meubles"),
    ("sawmilling",              "Sawmilling",               "Sägewerksarbeit",              "Aserrado",                      "Sciage"),
    ("earthworks",              "Earthworks & Landscaping", "Erdarbeiten",                  "Movimiento de Tierras",         "Terrassement"),
    ("fencing",                 "Fencing",                  "Zaunbau",                      "Construcción de Cercas",        "Pose de Clôtures"),

    # ── Energy & Environment ─────────────────────────────────────────────────
    ("solar-panel-installation","Solar Panel Installation", "Solaranlageninstallation",     "Instalación de Paneles Solares","Installation Panneaux Solaires"),
    ("photovoltaic-systems",    "Photovoltaic Systems",     "Photovoltaikanlagen",          "Sistemas Fotovoltaicos",        "Systèmes Photovoltaïques"),
    ("wind-energy",             "Wind Energy",              "Windenergie",                  "Energía Eólica",                "Énergie Éolienne"),
    ("biogas-systems",          "Biogas Systems",           "Biogasanlagen",                "Sistemas de Biogás",            "Systèmes de Biogaz"),
    ("rainwater-harvesting",    "Rainwater Harvesting",     "Regenwassergewinnung",         "Recolección de Agua de Lluvia", "Collecte d'Eau de Pluie"),
    ("greywater-treatment",     "Greywater Treatment",      "Grauwasserbehandlung",         "Tratamiento de Aguas Grises",   "Traitement des Eaux Grises"),
    ("energy-auditing",         "Energy Auditing",          "Energieaudit",                 "Auditoría Energética",          "Audit Énergétique"),
    ("forest-management",       "Forest Management",        "Forstwirtschaft",              "Gestión Forestal",              "Gestion Forestière"),
    ("reforestation",           "Reforestation",            "Aufforstung",                  "Reforestación",                 "Reboisement"),
    ("soil-science",            "Soil Science",             "Bodenkunde",                   "Ciencia del Suelo",             "Science du Sol"),
    ("water-retention",         "Water Retention Landscapes","Wasserretentionslandschaften", "Paisajes de Retención de Agua", "Paysages de Rétention d'Eau"),
    ("biochar-production",      "Biochar Production",       "Pflanzenkohleherstellung",     "Producción de Biochar",         "Production de Biochar"),
    ("off-grid-systems",        "Off-Grid Systems",         "Inselanlagen",                 "Sistemas Autónomos",            "Systèmes Autonomes"),
    ("solar-cooking",           "Solar Cooking",            "Solarkochen",                  "Cocina Solar",                  "Cuisine Solaire"),
    ("wind-turbines",           "Wind Turbines",            "Windkraftanlagen",             "Turbinas Eólicas",              "Éoliennes"),
    ("biodigesters",            "Biodigester Construction", "Biodigester-Bau",              "Construcción de Biodigestores", "Construction de Biodigesteurs"),
    ("water-system-maintenance","Water System Maintenance", "Wartung von Wassersystemen",   "Mantenimiento de Sistemas de Agua","Maintenance des Systèmes d'Eau"),
    ("spring-capture",          "Spring Water Capture",     "Quellfassung",                 "Captación de Manantiales",      "Captage de Source"),
    ("constructed-wetlands",    "Constructed Wetlands",     "Pflanzenkläranlagen",          "Humedales Artificiales",        "Phytoépuration"),
    ("micro-hydro",             "Micro Hydro Power",        "Kleinwasserkraft",             "Microhidroenergía",             "Micro Hydroélectricité"),
    ("solar-thermal",           "Solar Thermal Systems",    "Solarthermie",                 "Sistemas Solares Térmicos",     "Systèmes Solaires Thermiques"),
    ("water-pump-systems",      "Water Pump Systems",       "Pumpensysteme",                "Sistemas de Bombeo de Agua",    "Systèmes de Pompage"),
    ("fire-prevention",         "Wildfire Prevention",      "Brandschutz & Feuerprävention","Prevención de Incendios",       "Prévention des Incendies"),
    ("ecosystem-restoration",   "Ecosystem Restoration",    "Ökosystem-Renaturierung",      "Restauración de Ecosistemas",   "Restauration des Écosystèmes"),


    # ── Crafts & Textiles ────────────────────────────────────────────────────
    ("weaving",                 "Weaving",                  "Weben",                        "Tejido en Telar",               "Tissage"),
    ("spinning",                "Spinning",                 "Spinnen",                      "Hilado",                        "Filage"),
    ("sewing",                  "Sewing",                   "Nähen",                        "Costura",                       "Couture"),
    ("natural-dyeing",          "Natural Dyeing",           "Natürliches Färben",           "Tintorería Natural",            "Teinture Naturelle"),
    ("pottery",                 "Pottery",                  "Töpfern",                      "Alfarería",                     "Poterie"),
    ("basketweaving",           "Basketweaving",            "Korbflechten",                 "Cestería",                      "Vannerie"),
    ("leather-working",         "Leather Working",          "Lederverarbeitung",            "Marroquinería",                 "Maroquinerie"),
    ("felting",                 "Felting",                  "Filzen",                       "Fieltro",                       "Feutrage"),
    ("knitting",                "Knitting",                 "Stricken",                     "Tejido de Punto",               "Tricot"),
    ("candle-making",           "Candle Making",            "Kerzenherstellung",            "Elaboración de Velas",          "Fabrication de Bougies"),
    ("soapmaking",              "Soapmaking",               "Seifenherstellung",            "Elaboración de Jabón",          "Savonnerie"),
    ("wood-carving",            "Wood Carving",             "Holzschnitzerei",              "Talla en Madera",               "Sculpture sur Bois"),
    ("tool-sharpening",         "Tool Sharpening",          "Werkzeugschleifen",            "Afilado de Herramientas",       "Affûtage d'Outils"),
    ("mending-and-repair",      "Mending & Repair",         "Reparieren und Flicken",       "Remiendo y Reparación",         "Ravaudage et Réparation"),
    ("firewood-processing",     "Firewood Processing",      "Brennholzverarbeitung",        "Procesamiento de Leña",         "Préparation du Bois de Chauffage"),
    ("machinery-operation",     "Heavy Machinery Operation", "Traktor- & Baggerbedienung",   "Manejo de Maquinaria Pesada",   "Conduite d'Engins et Tracteurs"),
    ("bulk-food-preservation",  "Large-Scale Food Preserv.", "Vorratshaltung & Großküchen-Kons.","Conservación a Gran Escala", "Conservation d'Aliments Grande Échelle"),
    ("well-drilling",           "Well Drilling & Water Logs","Brunnenbau & Hydrologie",     "Perforación de Pozos de Agua",  "Forage de Puits et Hydrologie"),
    ("bushcraft",               "Bushcraft",                "Bushcraft",                    "Bushcraft",                     "Bushcraft"),
    ("upcycling",               "Upcycling",                "Upcycling",                    "Upcycling",                     "Upcycling"),
    ("rope-making",             "Rope Making",              "Seilherstellung",              "Fabricación de Cuerdas",        "Fabrication de Cordes"),
    ("loom-weaving",            "Loom Weaving",             "Webstuhlweben",                "Tejido en Telar",               "Tissage sur Métier"),
    ("shoemaking",              "Shoemaking",               "Schuhmacherei",                "Fabricación de Calzado",        "Cordonnier"),
    ("metalworking",            "Metalworking",             "Metallbearbeitung",            "Trabajo en Metal",              "Travail du Métal"),
    ("bike-building",           "Bicycle Building",         "Fahrradbau",                   "Construcción de Bicicletas",    "Construction de Vélos"),

    # ── Health & Wellness ────────────────────────────────────────────────────
    ("first-aid",               "First Aid",                "Erste Hilfe",                  "Primeros Auxilios",             "Premiers Secours"),
    ("herbal-medicine",         "Herbal Medicine",          "Pflanzenheilkunde",            "Medicina Herbal",               "Phytothérapie"),
    ("massage-therapy",         "Massage Therapy",          "Massagetherapie",              "Masoterapia",                   "Massage Thérapeutique"),
    ("yoga",                    "Yoga",                     "Yoga",                         "Yoga",                          "Yoga"),
    ("meditation",              "Meditation",               "Meditation",                   "Meditación",                    "Méditation"),
    ("midwifery",               "Midwifery",                "Hebammenarbeit",               "Partería",                      "Sage-Femme"),
    ("mental-health-support",   "Mental Health Support",    "Psychosoziale Unterstützung",  "Apoyo en Salud Mental",         "Soutien en Santé Mentale"),
    ("nutrition",               "Nutrition",                "Ernährung",                    "Nutrición",                     "Nutrition"),
    ("somatic-practices",       "Somatic Practices",        "Somatische Praktiken",         "Prácticas Somáticas",           "Pratiques Somatiques"),
    ("phytotherapy",            "Phytotherapy",             "Phytotherapie",                "Fitoterapia",                   "Phytothérapie"),
    ("traditional-chinese-med", "Traditional Chinese Med.","Trad. Chinesische Medizin",    "Medicina Tradicional China",    "Médecine Trad. Chinoise"),
    ("acupuncture",             "Acupuncture",              "Akupunktur",                   "Acupuntura",                    "Acupuncture"),
    ("chiropractic",            "Chiropractic",             "Chiropraktik",                 "Quiropráctica",                 "Chiropratique"),
    ("osteopathy",              "Osteopathy",               "Osteopathie",                  "Osteopatía",                    "Ostéopathie"),
    ("naturopathy",             "Naturopathy",              "Naturheilkunde",               "Naturopatía",                   "Naturopathie"),
    ("ayurveda",                "Ayurveda",                 "Ayurveda",                     "Ayurveda",                      "Ayurveda"),
    ("shiatsu",                 "Shiatsu",                  "Shiatsu",                      "Shiatsu",                       "Shiatsu"),
    ("aromatherapy",            "Aromatherapy",             "Aromatherapie",                "Aromaterapia",                  "Aromathérapie"),
    ("reflexology",             "Reflexology",              "Reflexzonenmassage",           "Reflexología",                  "Réflexologie"),
    ("elderly-care",            "Elderly Care",             "Altenpflege",                  "Cuidado de Personas Mayores",   "Soins aux Personnes Âgées"),
    ("home-care",               "Home Care & Nursing",      "Häusliche Pflege",             "Asistencia Domiciliaria",       "Soins à Domicile"),
    ("social-work",             "Social Work",              "Soziale Arbeit",               "Trabajo Social",                "Travail Social"),
    ("home-economics",          "Home Economics",           "Hauswirtschaft",               "Economía Doméstica",            "Économie Domestique"),
    ("communal-cooking",        "Communal Cooking",         "Gemeinschaftskochen",          "Cocina Comunitaria",            "Cuisine Communautaire"),
    ("disability-support",      "Disability Support",       "Behindertenbetreuung",         "Apoyo a la Discapacidad",       "Accompagnement du Handicap"),
    ("crisis-intervention",     "Crisis Intervention",      "Krisenintervention",           "Intervención en Crisis",        "Intervention de Crise"),
    ("childcare",               "Childcare",                "Kinderbetreuung",              "Cuidado Infantil",              "Garde d'Enfants"),
    ("burnout-prevention",      "Burnout Prevention",       "Burnout-Prävention",           "Prevención del Desgaste (Burnout)","Prévention de l'Épuisement"),
    ("space-holding",           "Emotional Space Holding",  "Emotionales Halten von Räumen","Sostén de Espacios Emocionales","Soutien des Espaces Émotionnels"),
    ("pedagogy",                "Pedagogy",                 "Pädagogik",                    "Pedagogía",                     "Pédagogie"),
    ("cooking",                 "Cooking",                  "Kochen",                       "Cocina",                        "Cuisine"),
    ("cleaning",                "Cleaning",                 "Putzen",                       "Limpieza",                      "Ménage"),
    ("psychotherapy",           "Psychotherapy",            "Psychotherapie",               "Psicoterapia",                  "Psychothérapie"),
    ("music-therapy",           "Music Therapy",            "Musiktherapie",                "Musicoterapia",                 "Musicothérapie"),
    ("behavioral-therapy",      "Behavioral Therapy",       "Verhaltenstherapie",           "Terapia Conductual",            "Thérapie Comportementale"),
    ("psychoanalysis",          "Psychoanalysis",           "Psychoanalyse",                "Psicoanálisis",                 "Psychanalyse"),
    ("depth-psychology",        "Depth Psychology",         "Tiefenpsychologie",            "Psicología Profunda",           "Psychologie des Profondeurs"),
    ("gestalt-therapy",         "Gestalt Therapy",          "Gestalttherapie",              "Terapia Gestalt",               "Gestalt-thérapie"),
    ("heros-journey",           "Hero's Journey Workshop",  "Heldenreise",                  "El Viaje del Héroe",            "Le Voyage du Héros"),
    ("dancing",                 "Dancing",                  "Tanzen",                       "Danza",                         "Danse"),
    ("dance-therapy",           "Dance Therapy",            "Tanztherapie",                 "Danzaterapia",                  "Dansthérapie"),
    ("movement-therapy",        "Movement Therapy",         "Bewegungstherapie",            "Terapia de Movimiento",         "Thérapie par le Mouvement"),
    ("physiotherapy",           "Physiotherapy",            "Physiotherapie",               "Fisioterapia",                  "Physiothérapie"),
    ("nutritional-counseling",  "Nutritional Counseling",   "Ernährungsberatung",           "Asesoramiento Nutricional",     "Conseil Nutritionnel"),
    ("dental-technology",       "Dental Technology",        "Zahntechnik",                  "Tecnología Dental",             "Technologie Dentaire"),
    ("ecstatic-dance",          "Ecstatic Dance",           "Ecstatic Dance",               "Danza Éxtasis",                 "Danse Extatique"),
    ("flow-arts",               "Flow Arts",                "Flow Arts (Jonglage/Feuer)",   "Artes del Flow",                "Arts du Flow"),
    ("slacklining",             "Slacklining",              "Slacklining",                  "Slackline",                     "Slackline"),
    ("breathwork",              "Breathwork",               "Atemarbeit",                   "Trabajo de Respiración",        "Travail du Souffle"),
    ("cacao-ceremonies",        "Cacao Ceremonies",         "Kakaozeremonien",              "Ceremonias de Cacao",           "Cérémonies du Cacao"),
    ("reiki",                   "Reiki",                    "Reiki",                        "Reiki",                         "Reiki"),
    ("tarot-reading",           "Tarot Reading",            "Tarot-Kartenlegen",            "Lectura de Tarot",              "Lecture de Tarot"),
    ("astrology",               "Astrology",                "Astrologie",                   "Astrología",                    "Astrologie"),
    ("natural-cosmetics",       "Natural Cosmetics",        "Naturkosmetik",                "Cosmética Natural",             "Cosmétique Naturelle"),
    ("macrame",                 "Macrame",                  "Makramee",                     "Macramé",                       "Macramé"),
    ("contact-improvisation",   "Contact Improvisation",    "Contact Improvisation",        "Improvisación de Contacto",     "Contact Improvisation"),
    ("acro-yoga",               "Acro Yoga",                "Acro Yoga",                    "Acro Yoga",                     "Acro Yoga"),
    ("shamanism",               "Shamanism",                "Schamanismus",                 "Chamanismo",                    "Chamanisme"),
    ("circle-dancing",          "Circle Dancing",           "Kreistänze",                   "Danzas Circulares",             "Danses Circulaires"),
    ("trauma-support",          "Trauma Support",           "Trauma-Begleitung",            "Apoyo para Trauma",             "Accompagnement du Trauma"),
    ("peer-counseling",         "Peer Counseling",          "Peer-Beratung",                "Acompañamiento entre Iguales",  "Soutien entre Pairs"),
    ("menstrual-health",        "Menstrual Health",         "Menstruationsgesundheit",      "Salud Menstrual",               "Santé Menstruelle"),
    ("birth-support",           "Birth Support",            "Geburtsbegleitung",            "Acompañamiento de Parto",       "Accompagnement à la Naissance"),
    ("grief-support",           "Grief Support",            "Trauerbegleitung",             "Acompañamiento en Duelo",       "Accompagnement du Deuil"),
    ("addiction-support",       "Addiction Support",        "Suchtbegleitung",              "Apoyo en Adicciones",           "Accompagnement des Addictions"),
    ("massage",                 "Massage",                  "Massage",                      "Masaje",                        "Massage"),
    ("timekeeping-support",     "Timekeeping Support",      "Zeitmanagement im Alltag",     "Gestión del Tiempo",            "Gestion du Temps"),
    ("errand-running",          "Errand Running",           "Besorgungen",                  "Recados",                       "Courses"),
    ("swedish-massage",         "Swedish Massage",          "Klassische Massage",           "Masaje Sueco",                  "Massage Suédois"),
    ("thai-massage",            "Thai Massage",             "Thaimassage",                  "Masaje Tailandés",              "Massage Thaï"),
    ("deep-tissue-massage",     "Deep Tissue Massage",      "Tiefengewebsmassage",          "Masaje de Tejido Profundo",     "Massage des Tissus Profonds"),
    ("sports-massage",          "Sports Massage",           "Sportmassage",                 "Masaje Deportivo",              "Massage Sportif"),
    ("lymphatic-drainage",      "Lymphatic Drainage",       "Lymphdrainage",                "Drenaje Linfático",             "Drainage Lymphatique"),
    ("reflexology-foot",        "Reflexology (Feet)",       "Fußreflexzonenmassage",        "Reflexología Podal",            "Réflexologie Plantaire"),
    ("reflexology-hand",        "Hand Reflexology",         "Handreflexzonenmassage",       "Reflexología de Manos",         "Réflexologie des Mains"),
    ("lomi-lomi",               "Lomi Lomi Massage",        "Lomi Lomi",                    "Masaje Lomi Lomi",              "Massage Lomi Lomi"),
    ("ayurvedic-abhyanga",      "Ayurvedic Abhyanga",       "Ayurvedische Abhyanga-Massage","Masaje Abhyanga",               "Massage Abhyanga Ayurvédique"),
    ("tuina",                   "Tui Na",                   "Tuina (TCM Massage)",          "Tuina",                         "Tuina"),
    ("craniosacral-therapy",    "Craniosacral Therapy",     "Kraniosakraltherapie",         "Terapia Craneosacral",          "Thérapie Craniosacrale"),
    ("trigger-point-therapy",   "Trigger Point Therapy",    "Triggerpunkt-Therapie",        "Terapia de Puntos Gatillo",     "Thérapie des Points Gâchettes"),
    ("myofascial-release",      "Myofascial Release",       "Faszientherapie",              "Liberación Miofascial",         "Libération Myofasciale"),
    ("aromatherapy-massage",    "Aromatherapy Massage",     "Aromamassage",                 "Masaje Aromaterapéutico",       "Massage Aromathérapeutique"),
    ("hot-stone-massage",       "Hot Stone Massage",        "Hot-Stone-Massage",            "Masaje con Piedras Calientes",  "Massage aux Pierres Chaudes"),
    ("bamboo-massage",          "Bamboo Massage",           "Bambusmassage",                "Masaje con Bambú",              "Massage au Bambou"),
    ("kahuna-bodywork",         "Hawaiian Lomi/Kahuna Bodywork","Kahuna Körperarbeit",      "Trabajo Corporal Kahuna",       "Travail Corporel Kahuna"),
    ("balinese-massage",        "Balinese Massage",         "Balinesische Massage",         "Masaje Balinés",                "Massage Balinais"),
    ("osteopathic-techniques",  "Osteopathic Techniques",   "Osteopathische Techniken",     "Técnicas Osteopáticas",         "Techniques Ostéopathiques"),
    ("hatha-yoga",              "Hatha Yoga",               "Hatha Yoga",                   "Hatha Yoga",                    "Hatha Yoga"),
    ("ashtanga-yoga",           "Ashtanga Yoga",            "Ashtanga Yoga",                "Ashtanga Yoga",                 "Ashtanga Yoga"),
    ("vinyasa-yoga",            "Vinyasa Yoga",             "Vinyasa Yoga",                 "Vinyasa Yoga",                  "Vinyasa Yoga"),
    ("iyengar-yoga",            "Iyengar Yoga",             "Iyengar Yoga",                 "Iyengar Yoga",                  "Iyengar Yoga"),
    ("kundalini-yoga",          "Kundalini Yoga",           "Kundalini Yoga",               "Kundalini Yoga",                "Kundalini Yoga"),
    ("yin-yoga",                "Yin Yoga",                 "Yin Yoga",                     "Yin Yoga",                      "Yin Yoga"),
    ("restorative-yoga",        "Restorative Yoga",         "Restorative Yoga",             "Yoga Restaurativa",             "Yoga Restauratif"),
    ("power-yoga",              "Power Yoga",               "Power Yoga",                   "Power Yoga",                    "Power Yoga"),
    ("jivamukti-yoga",          "Jivamukti Yoga",           "Jivamukti Yoga",               "Jivamukti Yoga",                "Jivamukti Yoga"),
    ("sivananda-yoga",          "Sivananda Yoga",           "Sivananda Yoga",               "Sivananda Yoga",                "Sivananda Yoga"),
    ("bikram-hot-yoga",         "Bikram / Hot Yoga",        "Bikram / Hot Yoga",            "Bikram / Hot Yoga",             "Bikram / Hot Yoga"),
    ("kripalu-yoga",            "Kripalu Yoga",             "Kripalu Yoga",                 "Kripalu Yoga",                  "Kripalu Yoga"),
    ("svaroopa-yoga",           "Svaroopa Yoga",            "Svaroopa Yoga",                "Svaroopa Yoga",                 "Svaroopa Yoga"),
    ("integral-yoga",           "Integral Yoga",            "Integral Yoga",                "Yoga Integral",                 "Yoga Intégral"),
    ("tantra-yoga",             "Tantra Yoga",              "Tantra Yoga",                  "Tantra Yoga",                   "Tantra Yoga"),
    ("raja-yoga",               "Raja Yoga",                "Raja Yoga",                    "Raja Yoga",                     "Raja Yoga"),
    ("karma-yoga",              "Karma Yoga",               "Karma Yoga",                   "Karma Yoga",                    "Karma Yoga"),
    ("bhakti-yoga",             "Bhakti Yoga",              "Bhakti Yoga",                  "Bhakti Yoga",                   "Bhakti Yoga"),
    ("jnana-yoga",              "Jnana Yoga",               "Jnana Yoga",                   "Jnana Yoga",                    "Jnana Yoga"),
    ("aerial-yoga",             "Aerial Yoga",              "Aerial Yoga",                  "Yoga Aéreo",                    "Yoga Aérien"),
    ("nada-yoga",               "Nada Yoga",                "Sound Yoga (Nada)",            "Yoga del Sonido",               "Yoga du Son"),
    ("prenatal-yoga",           "Prenatal Yoga",            "Prenatal Yoga",                "Yoga Prenatal",                 "Yoga Prénatal"),
    ("therapeutic-yoga",        "Therapeutic Yoga",         "Therapeutisches Yoga",         "Yoga Terapéutico",              "Yoga Thérapeutique"),
    ("feldenkrais-method",      "Feldenkrais Method",       "Feldenkrais-Methode",          "Método Feldenkrais",            "Méthode Feldenkrais"),
    ("alexander-technique",     "Alexander Technique",      "Alexander-Technik",            "Técnica Alexander",             "Technique Alexander"),
    ("body-mind-centering",     "Body-Mind Centering",      "Body-Mind Centering",          "Body-Mind Centering",           "Body-Mind Centering"),
    ("ideokinesis",             "Ideokinesis",              "Ideokinese",                   "Ideokinesis",                   "Idéokinésie"),
    ("eutony",                  "Eutony",                   "Eutonie",                      "Eutonía",                       "Eutonie"),
    ("bartenieff-fundamentals", "Bartenieff Fundamentals",  "Bartenieff-Grundlagen",        "Fundamentos Bartenieff",        "Fondamentaux Bartenieff"),
    ("laban-movement-analysis", "Laban Movement Analysis",  "Laban-Bewegungsanalyse",       "Análisis del Movimiento Laban","Analyse du Mouvement Laban"),
    ("rolfing",                 "Rolfing / Structural Integration","Rolfing / Strukturelle Integration","Integración Estructural (Rolfing)","Intégration Structurelle (Rolfing)"),
    ("somatic-experiencing",    "Somatic Experiencing",     "Somatic Experiencing",         "Experiencia Somática",          "Somatic Experiencing"),
    ("vipassana-meditation",    "Vipassana Meditation",    "Vipassana-Meditation",          "Meditación Vipassana",          "Méditation Vipassana"),
    ("zen-meditation",          "Zen Meditation",          "Zen-Meditation",                "Meditación Zen",                "Méditation Zen"),
    ("mindfulness-meditation",  "Mindfulness Meditation",  "Achtsamkeitsmeditation",        "Meditación de Atención Plena",  "Méditation de Pleine Conscience"),
    ("transcendental-meditation","Transcendental Meditation","Transzendentale Meditation",  "Meditación Trascendental",      "Méditation Transcendantale"),
    ("loving-kindness-meditation","Loving-Kindness Meditation","Metta-Meditation",          "Meditación de Amor Bondadoso",  "Méditation de Bienveillance"),
    ("body-scan-meditation",    "Body Scan Meditation",    "Bodyscan-Meditation",           "Escaneo Corporal",              "Scan Corporel"),
    ("yoga-nidra",              "Yoga Nidra",              "Yoga Nidra",                    "Yoga Nidra",                    "Yoga Nidra"),
    ("shamanic-journeying",     "Shamanic Journeying",     "Schamanische Reise",            "Viaje Chamánico",               "Voyage Chamanique"),
    ("breath-awareness",        "Breath Awareness",        "Atembeobachtung",               "Conciencia de la Respiración",  "Conscience du Souffle"),
    ("walking-meditation",      "Walking Meditation",      "Gehmeditation",                 "Meditación Caminando",          "Méditation Marchée"),
    ("mantra-meditation",       "Mantra Meditation",       "Mantra-Meditation",             "Meditación con Mantra",         "Méditation Mantra"),


    # ── Education & Community ────────────────────────────────────────────────
    ("teaching",                "Teaching",                 "Unterrichten",                 "Enseñanza",                     "Enseignement"),
    ("facilitation",            "Facilitation",             "Moderation",                   "Facilitación",                  "Facilitation"),
    ("conflict-mediation",      "Conflict Mediation",       "Konfliktmediation",            "Mediación de Conflictos",       "Médiation de Conflits"),
    ("deep-ecology",            "Deep Ecology",             "Tiefenökologie",               "Ecología Profunda",             "Écologie Profonde"),
    ("nonviolent-communication","Nonviolent Communication", "Gewaltfreie Kommunikation",    "Comunicación No Violenta",      "Communication Non-Violente"),
    ("project-management",      "Project Management",       "Projektmanagement",            "Gestión de Proyectos",          "Gestion de Projet"),
    ("event-organisation",      "Event Organisation",       "Veranstaltungsorganisation",   "Organización de Eventos",       "Organisation d'Événements"),
    ("community-organising",    "Community Organising",     "Gemeinschaftsorganisation",    "Organización Comunitaria",      "Organisation Communautaire"),
    ("language-teaching",       "Language Teaching",        "Sprachunterricht",             "Enseñanza de Idiomas",          "Enseignement des Langues"),
    ("coaching",                "Coaching",                 "Coaching",                     "Coaching",                      "Coaching"),
    ("sociocracy",              "Sociocracy",               "Soziokratie",                  "Sociocracia",                   "Sociocratie"),
    ("fundraising",             "Fundraising",              "Spendenakquise",               "Recaudación de Fondos",         "Collecte de Fonds"),
    ("consensus-decision",      "Consensus Decision-Making","Konsensentscheidungsfindung",  "Toma de Decisiones por Consenso","Prise de Décision par Consensus"),
    ("dragon-dreaming",         "Dragon Dreaming",          "Dragon Dreaming",              "Dragon Dreaming",               "Dragon Dreaming"),
    ("restorative-circles",     "Restorative Circles",      "Restorative Kreise",           "Círculos Restaurativos",        "Cercles Restauratifs"),
    ("community-governance",    "Community Governance",     "Gemeinschaftsverwaltung",      "Gobernanza Comunitaria",        "Gouvernance Communautaire"),
    ("zegg-forum",              "ZEGG Forum",               "ZEGG-Forum",                   "Foro ZEGG",                     "Forum ZEGG"),
    ("tzi-theme-centered",      "Theme-Centered Interaction","Themenzentrierte Interaktion","Interacción Centrada en el Tema","Interaction Centrée sur le Thème"),
    ("sociocracy-3",            "Sociocracy 3.0",           "Soziokratie 3.0",              "Sociocracia 3.0",               "Sociocratie 3.0"),
    ("systemic-consensusing",   "Systemic Consensusing",    "Systemisches Konsensieren",    "Consenso Sistémico",            "Consensus Systémique"),
    ("community-building",      "Community Building",       "Gemeinschaftsbildung",         "Construcción de Comunidad",     "Construction de Communauté"),
    ("wir-prozess",             "We-Process (Wir-Prozess)", "Wir-Prozess",                  "Proceso-Nosotros (Wir-Prozess)","Processus-Nous (Wir-Prozess)"),
    ("deep-democracy",          "Deep Democracy",           "Deep Democracy",               "Democracia Profunda",           "Démocratie Profonde"),
    ("open-space-technology",   "Open Space Technology",    "Open-Space-Methode",           "Tecnología de Espacio Abierto", "Technologie de l'Espace Ouvert"),
    ("world-cafe",              "World Café",               "World Café",                   "World Café",                    "World Café"),
    ("dynamic-facilitation",    "Dynamic Facilitation",     "Dynamic Facilitation",         "Facilitación Dinámica",         "Facilitation Dynamique"),
    ("car-sharing",             "Car-Sharing Fleet Setup",  "Carsharing Fuhrparkorganisation","Gestión de Autos Compartidos",  "Gestion de l'Autopartage"),
    ("tool-library-admin",      "Tool Library Management",  "Werkzeugbibliothek-Verwaltung","Gestión de Inventario de Herram.","Gestion de l'Outilthèque"),
    ("supply-chain-logistics",  "Bulk Buying Coordination", "Sammelbestellungen-Koordination","Coordinación de Compras al Por Mayor","Coordination d'Achats Groupés"),
    ("member-integration",      "New Member Onboarding",    "Gemeinschafts-Integration",    "Integración de Nuevos Miembros","Intégration de Nouveaux Membres"),
    ("human-design",            "Human Design",             "Human Design",                 "Diseño Humano",                 "Design Humain"),
    ("mayan-calendar",          "Mayan Calendar",           "Maya-Kalender",                "Calendario Maya",               "Calendrier Maya"),
    ("possibility-management",  "Possibility Management",   "Possibility Management",       "Gestión de Posibilidades",      "Gestion des Possibilités"),
    ("spiral-dynamics",         "Spiral Dynamics",          "Spiral Dynamics",              "Dinámica Espiral",              "Dynamique Spirale"),
    ("integral-theory",         "Integral Theory",          "Integrale Theorie",            "Teoría Integral",               "Théorie Intégrale"),
    ("family-constellations",   "Family Constellations",    "Familienaufstellung",          "Constelaciones Familiares",     "Constellations Familiales"),
    ("enneagram",               "Enneagram",                "Enneagramm",                   "Eneagrama",                     "Ennéagramme"),
    ("radical-honesty",         "Radical Honesty",          "Radikale Ehrlichkeit",         "Sinceridad Radical",            "Honnêteté Radicale"),
    ("shadow-work",             "Shadow Work",              "Schattenarbeit",               "Trabajo de Sombra",             "Travail de l'Ombre"),
    ("hosting",                 "Hosting & Guest Care",     "Gastfreundschaft",             "Hospitalidad",                  "Accueil et Hospitalité"),
    ("volunteer-coordination",  "Volunteer Coordination",   "Freiwilligenkoordination",     "Coordinación de Voluntarios",   "Coordination des Bénévoles"),
    ("kitchen-coordination",    "Kitchen Coordination",     "Küchenkoordination",           "Coordinación de Cocina",        "Coordination de Cuisine"),
    ("festival-production",     "Festival Production",      "Festivalorganisation",         "Producción de Festivales",      "Production de Festivals"),
    ("ritual-facilitation",     "Ritual Facilitation",      "Ritualbegleitung",             "Facilitación de Rituales",      "Facilitation de Rituels"),
    ("circle-facilitation",     "Circle Facilitation",      "Kreismoderation",              "Facilitación de Círculos",      "Facilitation de Cercle"),
    ("gift-economy",            "Gift Economy Practices",   "Schenkökonomie",               "Economía del Regalo",           "Économie du Don"),
    ("skillsharing",            "Skill Sharing",            "Fähigkeitentausch",            "Intercambio de Habilidades",    "Partage de Compétences"),
    ("meeting-note-taking",     "Meeting Note-Taking",      "Protokollieren",               "Toma de Notas",                 "Prise de Notes"),
    ("brainstorm-facilitation", "Light Brainstorming",      "Ideen-Moderation",             "Facilitación de Ideas",         "Facilitation d’Idées"),

    # ── Arts & Media ─────────────────────────────────────────────────────────
    ("music",                   "Music",                    "Musik",                        "Música",                        "Musique"),
    ("music-production",        "Music Production",         "Musikproduktion",              "Producción Musical",            "Production Musicale"),
    ("music-composition",       "Music Composition",        "Musikkomposition",             "Composición Musical",           "Composition Musicale"),
    ("singing",                 "Singing",                  "Singen",                       "Canto",                         "Chant"),
    ("piano",                   "Piano",                    "Klavier",                      "Piano",                         "Piano"),
    ("guitar",                  "Guitar",                   "Gitarre",                      "Guitarra",                      "Guitare"),
    ("drums",                   "Drums",                    "Schlagzeug",                   "Batería",                       "Batterie"),
    ("bass-guitar",             "Bass Guitar",              "Bassgitarre",                  "Bajo",                          "Basse"),
    ("violin",                  "Violin",                   "Violine",                      "Violín",                        "Violon"),
    ("flute",                   "Flute",                    "Flöte",                        "Flauta",                        "Flûte"),
    ("saxophone",               "Saxophone",                "Saxophon",                     "Saxofón",                       "Saxophone"),
    ("percussion",              "Percussion",               "Percussion",                   "Percusión",                     "Percussion"),
    ("photography",             "Photography",              "Fotografie",                   "Fotografía",                    "Photographie"),
    ("drawing-and-painting",    "Drawing & Painting",       "Zeichnen und Malen",           "Dibujo y Pintura",              "Dessin et Peinture"),
    ("graphic-design",          "Graphic Design",           "Grafikdesign",                 "Diseño Gráfico",                "Design Graphique"),
    ("video-production",        "Video Production",         "Videoproduktion",              "Producción de Vídeo",           "Production Vidéo"),
    ("theatre",                 "Theatre",                  "Theater",                      "Teatro",                        "Théâtre"),
    ("storytelling",            "Storytelling",             "Geschichtenerzählen",          "Narración",                     "Conte"),
    ("land-art",                "Land Art",                 "Land Art",                     "Arte de la Tierra",             "Land Art"),
    ("design",                  "Design",                   "Design",                       "Diseño",                        "Design"),
    ("web-design",              "Web Design",               "Webdesign",                    "Diseño Web",                    "Design Web"),
    ("social-media",            "Social Media",             "Social Media",                 "Redes Sociales",                "Réseaux Sociaux"),
    ("printing",                "Printing",                 "Drucken",                      "Impresión",                     "Impression"),
    ("lettering",               "Lettering",                "Handlettering",                "Rotulación",                    "Lettrage"),
    ("painting",                "Painting",                 "Malen",                        "Pintura",                       "Peinture"),
    ("djing",                   "DJing",                    "DJing",                        "DJing",                         "DJing"),
    ("sound-engineering",       "Sound Engineering",        "Tontechnik",                   "Ingeniería de Sonido",          "Ingénierie du Son"),
    ("live-streaming",          "Live Streaming",           "Livestreaming",                "Transmisión en Vivo",           "Streaming en Direct"),
    ("podcasting",              "Podcasting",               "Podcasting",                   "Podcasting",                    "Podcasting"),
    ("community-radio",         "Community Radio",          "Freies Radio",                 "Radio Comunitaria",             "Radio Communautaire"),
    ("live-electronics",        "Live Electronics",         "Live-Elektronik",              "Electrónica en Vivo",           "Électronique Live"),
    ("sound-design",            "Sound Design",             "Klanggestaltung",              "Diseño Sonoro",                 "Design Sonore"),
    ("field-recording",         "Field Recording",          "Field Recording",              "Grabación de Campo",            "Enregistrement de Terrain"),
    ("poi-spinning",            "Poi Spinning",             "Poi-Spinning",                 "Poi",                           "Poi"),
    ("staff-spinning",          "Staff Spinning",           "Stockdrehen",                  "Manejo de Bastón",              "Bâton"),
    ("contact-staff",           "Contact Staff",            "Contact Staff",                "Contact Staff",                 "Contact Staff"),
    ("double-staff",            "Double Staff",             "Double Staff",                 "Doble Bastón",                  "Double Bâton"),
    ("hula-hoop",               "Hula Hoop",                "Hula Hoop",                    "Hula Hoop",                     "Hula Hoop"),
    ("juggling-3-balls",        "Juggling (3 Balls)",       "3-Ball-Jonglage",              "Malabares (3 Pelotas)",           "Jonglage (3 Balles)"),
    ("juggling-4-balls",        "Juggling (4 Balls)",       "4-Ball-Jonglage",              "Malabares (4 Pelotas)",           "Jonglage (4 Balles)"),
    ("juggling-5-balls",        "Juggling (5 Balls)",       "5-Ball-Jonglage",              "Malabares (5 Pelotas)",           "Jonglage (5 Balles)"),
    ("juggling-6plus-balls",    "Advanced Juggling (6+)",   "Fortgeschrittene Jonglage",    "Malabares Avanzados (6+)",        "Jonglage Avancée (6+)"),
    ("contact-juggling",        "Contact Juggling",         "Contact Juggling",             "Contact Juggling",                "Contact Juggling"),
    ("fire-spinning",           "Fire Spinning",            "Feuerspinnen",                 "Malabares con Fuego",             "Jonglage de Feu"),
    ("fire-performance",        "Fire Performance",         "Feuershow",                    "Performance de Fuego",            "Performance de Feu"),
    ("dance-improvisation",     "Dance Improvisation",      "Tanzimprovisation",            "Improvisación de Danza",          "Improvisation Danse"),
    ("free-dance",              "Free Dance",               "Freies Tanzen",                "Danza Libre",                     "Danse Libre"),
    ("street-performance",      "Street Performance",       "Straßenkunst",                 "Arte Callejero",                  "Art de Rue"),
    ("circus-skills",           "Circus Skills",            "Zirkuskünste",                 "Habilidades Circenses",           "Arts du Cirque"),
    ("clowning",                "Clowning",                 "Clownerie",                    "Clown",                           "Clown"),
    ("impro-theatre",           "Improvisational Theatre",  "Improtheater",                 "Teatro de Impro",                 "Théâtre d'Impro"),

    # ── Technology ───────────────────────────────────────────────────────────
    ("web-development",         "Web Development",          "Webentwicklung",               "Desarrollo Web",                "Développement Web"),
    ("software-development",    "Software Development",     "Softwareentwicklung",          "Desarrollo de Software",        "Développement Logiciel"),
    ("electronics-repair",      "Electronics Repair",       "Elektronikreparatur",          "Reparación de Electrónica",     "Réparation Électronique"),
    ("bicycle-repair",          "Bicycle Repair",           "Fahrradreparatur",             "Reparación de Bicicletas",      "Réparation de Vélos"),
    ("3d-printing",             "3D Printing",              "3D-Druck",                     "Impresión 3D",                  "Impression 3D"),
    ("open-source-hardware",    "Open-Source Hardware",     "Open-Source-Hardware",         "Hardware de Código Abierto",    "Matériel Libre"),
    ("server-administration",   "Self-Hosting & SysAdmin",  "Server-Administration",        "Administración de Servidores",  "Administration de Serveurs"),
    ("mesh-networks",           "Community Mesh Networks",  "Freifunk & Mesh-Netzwerke",    "Redes Mesh Comunitarias",       "Réseaux Mesh Communautaires"),
    ("data-privacy-setup",      "Digital Privacy & Security","Datenschutz & Digitale Sicherheit","Privacidad y Seguridad Digital","Sécurité et Confidentialité Numérique"),
    ("linux-administration",    "Linux Administration",     "Linux-Administration",         "Administración Linux",          "Administration Linux"),
    ("networking",              "Networking",               "Netzwerktechnik",              "Redes Informáticas",            "Réseaux Informatiques"),
    ("repair-cafes",            "Repair Café Facilitation", "Repair-Café-Moderation",       "Facilitación de Repair Cafés",  "Animation de Repair Cafés"),
    ("appropriate-technology",  "Appropriate Technology",   "Angepasste Technologie",       "Tecnología Apropiada",          "Technologie Appropriée"),

    # ── Legal & Administration ───────────────────────────────────────────────────────
    ("bookkeeping",             "Bookkeeping",              "Buchführung",                  "Contabilidad",                  "Comptabilité"),
    ("grant-writing",           "Grant Writing",            "Förderantragstellung",         "Redacción de Subvenciones",     "Rédaction de Subventions"),
    ("translation",             "Translation",              "Übersetzung",                  "Traducción",                    "Traduction"),
    ("legal-advice",            "Legal Advice",             "Rechtsberatung",               "Asesoría Legal",                "Conseil Juridique"),
    ("research",                "Research",                 "Forschung",                    "Investigación",                 "Recherche"),
    ("cooperative-law",         "Association & Coop Law",   "Vereins- & Genossenschaftsrecht","Derecho de Asociaciones y Coop.","Droit des Assocs et Coopératives"),
    ("community-financing",     "Direct Loans & Crowdfunding","Direktkredite & Crowdfunding", "Préstamos Directos y Crowdfunding","Prêts Directs et Financement"),
    ("zoning-and-permits",      "Zoning Laws & Permits",    "Baurecht & Genehmigungen",     "Leyes de Zonificación y Permisos","Permis de Construire et Bureaucratie"),
    ("nonprofit-management",    "Nonprofit Management",     "Gemeinnützige Verwaltung",     "Gestión de ONG",                "Gestion Associative"),
    ("residency-coordination",  "Residency Coordination",   "Bewohnerkoordination",         "Coordinación de Residentes",    "Coordination des Résidents"),
    ("visa-support",            "Visa & Residency Support", "Visa- & Aufenthaltsberatung",  "Apoyo de Visados y Residencia", "Aide aux Visas et Résidence"),

    # ── Outdoor & Transport ──────────────────────────────────────────────────
    ("horse-riding-and-care",   "Horse Riding & Care",      "Reiten und Pferdepflege",      "Equitación y Cuidado de Caballos","Équitation et Soin des Chevaux"),
    ("navigation",              "Navigation & Orienteering","Navigation und Orientierung",  "Navegación y Orientación",      "Navigation et Orientation"),
    ("wilderness-survival",     "Wilderness Survival",      "Wildnisüberleben",             "Supervivencia en la Naturaleza","Survie dans la Nature"),
    ("car-mechanics",           "Car Mechanics",            "Kfz-Mechanik",                 "Mecánica de Automóviles",       "Mécanique Automobile"),
    ("chainsaw-operation",      "Chainsaw Operation",       "Kettensägenbetrieb",           "Manejo de Motosierra",          "Utilisation de Tronçonneuse"),
    ("cargo-bike-maintenance",  "Cargo Bike Maintenance",   "Lastenradwartung",             "Mantenimiento de Bici de Carga","Entretien de Vélo Cargo"),
    ("hitchhiking",             "Hitchhiking",              "Trampen",                      "Autoestop",                     "Auto-stop"),
    ("trail-building",          "Trail Building",           "Wegebau",                      "Construcción de Senderos",      "Construction de Sentiers"),
    ("animal-tracking",         "Animal Tracking",          "Tierspurenlesen",              "Rastreo de Animales",           "Pistage Animal"),
    ("camp-setup",              "Camp Setup",               "Camp-Aufbau",                  "Montaje de Campamentos",        "Installation de Camp"),
    ("offroad-driving",         "Offroad Driving",          "Geländefahren",                "Conducción Todoterreno",        "Conduite Tout-Terrain"),

    # ── High-Value Professional & Pro-Bono Services ──────────────────────────
    ("structural-engineering",  "Structural Engineering & Statics","Bauingenieurwesen & Statik","Ingeniería Estructural y Estática","Ingénierie Structurelle et Statique"),
    ("sustainable-architecture","Eco-Architecture & Blueprinting","Ökologische Architektur & Bauzeichnung","Arquitectura Ecológica y Planos","Architecture Écologique et Plans"),
    ("land-surveying-gis",      "Land Surveying & GIS Mapping", "Vermessungswesen & GIS-Kartierung","Topografía y Cartografía SIG", "Topographie et Cartographie SIG"),
    ("tax-advisory",            "Tax Consulting & Structuring", "Steuerberatung & Strukturierung","Asesoría Fiscal y Estructuración","Conseil Fiscal et Structuration"),
    ("real-estate-law",         "Real Estate & Contract Law",   "Immobilien- & Vertragsrecht",  "Derecho Inmobiliario y Contractual","Droit Immobilier et Contractuel"),
    ("general-medicine",        "General Medicine (MD)",        "Allgemeinmedizin (Arzt/Ärztin)","Medicina General",             "Médecine Générale"),
    ("veterinary-medicine",     "Veterinary Medicine",          "Tiermedizin (Veterinärmedizin)","Medicina Veterinaria",         "Médecine Vétérinaire"),
    ("dentistry",               "Dentistry & Oral Health",      "Zahnmedizin & Zahngesundheit", "Odontología y Salud Bucal",     "Dentisterie et Santé Bucco-Dentaire"),
    ("cybersecurity-engineering","Cybersecurity & Network Eng.","Cybersicherheit & Netzwerktechnik","Ciberseguridad e Ing. de Redes","Cybersécurité et Ing. Réseau"),
    ("devops-infrastructure",   "DevOps & Cloud Infrastructure","DevOps & Cloud-Infrastruktur","DevOps e Infraestructura Cloud","DevOps et Infrastructure Cloud"),
    ("impact-media-production", "Professional Filmmaking & PR", "Professionelle Filmproduktion & PR","Producción de Cine Profesional y RP","Réalisation de Films Pro et RP"),
    ("business-modeling",       "Eco-Ventures & Business Models","Gründungsberatung & Businessmodelle","Modelos de Negocio Sostenibles","Modèles d'Affaires Écoresponsables"),
    ("medical-practice",        "Medical Practice",         "Medizin (Arzt/Ärztin)",        "Medicina (Médico/a)",           "Médecine (Médecin)"),
    ("legal-counsel",           "Legal Counsel",            "Rechtsberatung (Anwalt/Anwältin)", "Asesoría Jurídica (Abogado/a)", "Conseil Juridique (Avocat/e)"),
    ("architecture",            "Architecture",             "Architektur",              "Arquitectura",                     "Architecture"),

        # ── Everyday Community Support ───────────────────────────────────────────
    ("dishwashing",             "Dishwashing",              "Spülen",                       "Lavar Platos",                  "Vaisselle"),
    ("kitchen-help",            "Kitchen Help",             "Küchenhilfe",                  "Ayuda en Cocina",               "Aide en Cuisine"),
    ("meal-preparation",        "Meal Preparation",         "Essensvorbereitung",           "Preparación de Comidas",        "Préparation des Repas"),
    ("vegetable-chopping",      "Vegetable Preparation",    "Gemüse schneiden",             "Preparación de Verduras",       "Préparation des Légumes"),
    ("serving-food",            "Serving Food",             "Essensausgabe",                "Servir Comida",                 "Service des Repas"),
    ("laundry",                 "Laundry",                  "Wäsche waschen",               "Lavandería",                    "Lessive"),
    ("housekeeping",            "Housekeeping",             "Haushaltspflege",              "Mantenimiento del Hogar",       "Entretien de Maison"),
    ("decluttering",            "Decluttering & Organising","Aufräumen & Ordnen",           "Ordenar y Organizar",           "Rangement et Organisation"),
    ("recycling-sorting",       "Recycling Sorting",        "Mülltrennung",                 "Clasificación de Reciclaje",    "Tri des Déchets"),
    ("waste-management",        "Waste Management",         "Abfallmanagement",             "Gestión de Residuos",           "Gestion des Déchets"),
    ("compost-maintenance",     "Compost Maintenance",      "Kompostpflege",                "Mantenimiento de Compost",      "Entretien du Compost"),
    ("firewood-stacking",       "Firewood Stacking",        "Holz stapeln",                 "Apilar Leña",                   "Empilage du Bois"),
    ("watering-plants",         "Watering Plants",          "Pflanzen gießen",              "Regar Plantas",                 "Arrosage des Plantes"),
    ("garden-maintenance",      "Garden Maintenance",       "Gartenpflege",                 "Mantenimiento del Jardín",      "Entretien du Jardin"),
    ("harvesting",              "Harvesting",               "Ernten",                       "Cosecha",                       "Récolte"),
    ("seed-sowing",             "Seed Sowing",              "Aussaat",                      "Siembra",                       "Semis"),
    ("path-maintenance",        "Path Maintenance",         "Wegepflege",                   "Mantenimiento de Caminos",      "Entretien des Sentiers"),
    ("painting-walls",          "Painting Walls",           "Wände streichen",              "Pintar Paredes",                "Peinture Murale"),
    ("sanding",                 "Sanding",                  "Schleifen",                    "Lijado",                        "Ponçage"),
    ("material-carrying",       "Carrying Materials",       "Material tragen",              "Transportar Materiales",        "Transport de Matériaux"),
    ("moving-help",             "Moving & Lifting Help",    "Umzugshilfe",                  "Ayuda con Mudanzas",            "Aide au Déménagement"),
    ("tool-cleaning",           "Tool Cleaning & Care",     "Werkzeugpflege",               "Limpieza de Herramientas",      "Entretien des Outils"),
    ("shopping-help",           "Shopping & Errands",       "Einkäufe & Besorgungen",       "Compras y Recados",             "Courses et Commissions"),
    ("driving-support",         "Driving Support",          "Fahrdienste",                  "Apoyo de Transporte",           "Aide au Transport"),
    ("guest-pickup",            "Guest Pickup",             "Gäste abholen",                "Recoger Huéspedes",             "Accueil Transport"),
    ("hosting-guests",          "Hosting Guests",           "Gäste betreuen",               "Hospedar Visitantes",           "Accueil des Visiteurs"),
    ("reception",               "Reception & Welcome",      "Empfang & Begrüßung",          "Recepción y Bienvenida",        "Accueil et Réception"),
    ("translation-help",        "Informal Translation Help","Sprachhilfe",                  "Ayuda de Traducción",           "Aide à la Traduction"),
    ("listening-support",       "Listening Support",        "Zuhören",                      "Escucha Activa",                "Écoute Active"),
    ("companionship",           "Companionship",            "Gesellschaft leisten",         "Acompañamiento",                "Compagnie"),
    ("child-supervision",       "Child Supervision",        "Kinder beaufsichtigen",        "Supervisión Infantil",          "Surveillance des Enfants"),
    ("pet-care",                "Pet Care",                 "Tierbetreuung",                "Cuidado de Mascotas",           "Soin des Animaux"),
    ("elder-support",           "Support for Elders",       "Unterstützung für Ältere",     "Apoyo a Personas Mayores",      "Soutien aux Aînés"),
    ("event-setup",             "Event Setup",              "Veranstaltungsaufbau",         "Montaje de Eventos",            "Installation d'Événements"),
    ("event-cleanup",           "Event Cleanup",            "Veranstaltungsabbau",          "Limpieza tras Eventos",         "Nettoyage d'Événements"),
    ("decoration",              "Decoration",               "Dekoration",                   "Decoración",                    "Décoration"),
    ("campfire-hosting",        "Campfire Hosting",         "Lagerfeuer gestalten",         "Facilitar Fogatas",             "Animation de Feu de Camp"),
    ("food-distribution",      "Bread & Food Distribution","Lebensmittel verteilen",       "Distribución de Alimentos",     "Distribution Alimentaire"),
]


class Command(BaseCommand):
    help = "Load the curated skill list into SkillTaxonomy (safe to re-run)"

    def handle(self, *args, **options):
        created = updated = 0
        for slug, en, de, es, fr in SKILLS:
            names = {"en": en, "de": de, "es": es, "fr": fr}
            obj, was_created = SkillTaxonomy.objects.update_or_create(
                slug=slug,
                defaults={"names": names},
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Done — {created} created, {updated} updated ({created + updated} total)"
        ))
