# Generated by Django 3.0.8 on 2021-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200716_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=150, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=150, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
