# Generated by Django 3.0.8 on 2021-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210319_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
