# Generated by Django 3.1.7 on 2021-03-21 16:09

from django.db import migrations, models
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210321_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About you'),
        ),
        migrations.AddField(
            model_name='user',
            name='ecobasa_what',
            field=models.TextField(blank=True, null=True, verbose_name='What would you like to use ecobasa mainly for?'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=osm_field.fields.OSMField(blank=True, lat_field='location_lat', lon_field='location_lon', null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=osm_field.fields.LatitudeField(blank=True, null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lon',
            field=osm_field.fields.LongitudeField(blank=True, null=True, validators=[osm_field.validators.validate_longitude]),
        ),
        migrations.AddField(
            model_name='user',
            name='world',
            field=models.TextField(blank=True, null=True, verbose_name='What do you do to make the world a better place?'),
        ),
    ]
