# Generated by Django 3.1.7 on 2021-03-24 00:26

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210321_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to='user-images', verbose_name='image'),
        ),
    ]
