# Generated by Django 4.2.28 on 2026-05-13 12:34

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("users", "0009_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
