# Generated by Django 4.2.28 on 2026-03-02 03:10

import communities.mixins
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True, verbose_name="What brings this community together?"
                    ),
                ),
                (
                    "accomodation",
                    models.TextField(
                        blank=True,
                        help_text="Where can your visitors sleep? Do you have space for a bus, tents? How is the indoor sleeping situation? Do you have mattresses, a couch? Donations or pricing model? Required daily work or experience?",
                        verbose_name="Accomodation for Guests",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="link of your communities website",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="telephone"
                    ),
                ),
                (
                    "video",
                    embed_video.fields.EmbedVideoField(
                        blank=True,
                        help_text="Link to a video showing your community",
                        max_length=255,
                        null=True,
                        verbose_name="Video",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inhabitants",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="How many people live in your community?",
                    ),
                ),
                (
                    "children",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="how many children live at your place?",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum number of people you can host",
                    ),
                ),
                (
                    "has_workshop_space",
                    models.TextField(
                        blank=True,
                        help_text="Describe your workshop spaces and what people can build/construct/manufacture.",
                        verbose_name="Do you have workshop spaces where people can build/construct/manufacture things?",
                    ),
                ),
                (
                    "offers_seminars",
                    models.TextField(
                        blank=True,
                        help_text="List seminars, topics, and how visitors can join.",
                        verbose_name="Do you offer any seminars that visitors could attend?",
                    ),
                ),
                (
                    "visitor_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Anything guests must know before arriving: expectations, minimum length of stay, costs, working hours, house rules.",
                        verbose_name="Requirements for visitors",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p", "Future Project (looking for co-founders)"),
                            ("s", "Starting Project (first years)"),
                            ("e", "Established (+4 years)"),
                        ],
                        default="e",
                        max_length=2,
                        verbose_name="Project status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("e", "Ecovillage"),
                            ("c", "Commune"),
                            ("h", "Houseproject"),
                            ("f", "Permaculture Farm"),
                            ("p", "Place for Projects"),
                        ],
                        default="e",
                        max_length=2,
                        verbose_name="Type of community",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="Geo Location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community",
                "verbose_name_plural": "Communities",
                "ordering": ["name"],
            },
            bases=(communities.mixins.UniqueSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TaggedSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.community",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaggedCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.community",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="community-images/", verbose_name="Image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="community",
            name="skills",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Skills that people can learn by volunteering or staying in your community",
                through="communities.TaggedSkills",
                to="taggit.Tag",
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Add some keywords that define your community. This way your profile can be found by in the search. People might be interested in your technologies, structures or experiences.",
                through="communities.TaggedCommunity",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
