# Generated by Django 4.2.28 on 2026-03-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="tags",
        ),
        migrations.DeleteModel(
            name="TaggedCommunity",
        ),
    ]
