# Generated by Django 3.1.7 on 2021-03-23 08:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210321_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='accomodation',
            field=models.TextField(blank=True, help_text='Where can your visitors sleep? Do you have space for a bus, tents? How is the indoor sleeping situation? Do you have matresses, a couch? Do you have a donations or a pricing model? Required daily working amount or epxeriences?', verbose_name='Accomodation for Guests'),
        ),
        migrations.AddField(
            model_name='community',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='how many children live at your place?'),
        ),
        migrations.AddField(
            model_name='community',
            name='inhabitants',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='how many people live in your community?'),
        ),
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Future Project (looking for co-founders)'), ('s', 'Starting Project (first years)'), ('e', 'Established (+4 years)')], default='e', max_length=2, verbose_name='Project status'),
        ),
        migrations.AddField(
            model_name='community',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telephone'),
        ),
        migrations.AddField(
            model_name='community',
            name='type',
            field=models.CharField(blank=True, choices=[('e', 'Ecovillage'), ('c', 'Commune'), ('h', 'Houseproject'), ('f', 'Permaculture Farm'), ('p', 'Place for Projects')], default='e', max_length=2, verbose_name='Type of community'),
        ),
        migrations.AddField(
            model_name='community',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Link to a video showing your community', max_length=255, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='community',
            name='vision',
            field=models.TextField(blank=True, verbose_name='What brings this community together?'),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='link of your communities website'),
        ),
    ]
