# Generated by Django 3.1.7 on 2021-03-23 12:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('communities', '0003_auto_20210323_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_taggedskills_items', to='taggit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_taggedcommunity_items', to='taggit.tag')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='Skills that people can learn by volunteering or staying in your community', related_name='_skills', through='communities.TaggedSkills', to='taggit.Tag', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add some keywords that define your community. This way your profile can be found by in the search. People might be interested in your technologies, structures or experiences.', related_name='_tags', through='communities.TaggedCommunity', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
