# These are supported funding model platforms

# github: [ecobasa]
donorbox: [https://donorbox.org/ecobasa-hosting-2021]
coinbase: [https://commerce.coinbase.com/checkout/0ae56c46-901d-48bf-8b2a-5e51f6a7637e]
liberapay: ecobasa.org
flattr: [https://flattr.com/@ecobasa.org]
patreon: https://www.patreon.com/arnology?fan_landing=true