version: '2'

networks:
  backend:
    driver: bridge

services:
  
  database:
    image: kartoza/postgis
    env_file:
      - ./postgres.env
    networks:
      - backend
  
  django:
    build:
      context: .
      dockerfile: dockerfile.devel
    env_file:
      - ./django.env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/services/ecobasa
    depends_on:
      - database
    networks:
      - backend
    ports:
      - "127.0.0.1:8000:8000"
  
  watch:
    image: node
    volumes:
      - .:/opt/services/ecobasa
    working_dir: /opt/services/ecobasa
    command: bash -c "npm install && npm run watch"

