# start from an official image
FROM python:3.8

ENV PYTHONUNBUFFERED=1

# arbitrary location choice: you can change the directory
RUN mkdir -p /opt/services/ecobasa
WORKDIR /opt/services/ecobasa

# copy our project code
COPY ./ /opt/services/ecobasa/

# install our dependencies
RUN pip install pipenv
RUN pipenv install --dev --system
RUN apt-get update && apt-get install -y \
	binutils\ 
	libproj-dev\ 
	gdal-bin

# expose the port 8000
EXPOSE 8000