# Generated by Django 3.0.8 on 2020-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('offer', 'Offer'), ('wish', 'Wish')], max_length=5, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
