# Generated by Django 3.0.8 on 2020-07-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
    ]
