# Generated by Django 3.0.8 on 2020-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0002_auto_20200714_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='random_id',
            field=models.CharField(default='afjzhuop', editable=False, max_length=8, verbose_name='Random Id'),
            preserve_default=False,
        ),
    ]
