# Generated by Django 3.0.8 on 2020-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0003_ad_random_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='random_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Random Id'),
        ),
    ]
