# Generated by Django 3.0.8 on 2020-07-14 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0004_auto_20200714_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='random_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='Random Id'),
        ),
    ]
