# Generated by Django 3.0.8 on 2020-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0007_auto_20200716_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Ad Category', 'verbose_name_plural': 'Ad Categories'},
        ),
        migrations.AddField(
            model_name='adcategory',
            name='order',
            field=models.IntegerField(default='0', verbose_name='Order'),
        ),
    ]
