# Generated by Django 3.0.8 on 2020-07-23 11:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0010_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
