# Generated by Django 3.0.8 on 2020-07-26 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0011_auto_20200723_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Geo Location'),
        ),
    ]
