# Generated by Django 3.1.7 on 2021-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0012_auto_20200726_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifting-images', verbose_name='image'),
        ),
    ]
