# Generated by Django 4.2.30 on 2026-05-18 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifting", "0014_alter_adcategory_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("my_place", "My place — come pick up / visit me"),
                            ("your_place", "Your place — I will bring it / visit you"),
                            ("custom", "Somewhere else"),
                        ],
                        default="your_place",
                        max_length=20,
                        verbose_name="Meeting location",
                    ),
                ),
                (
                    "proposed_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Custom location"
                    ),
                ),
                ("proposed_lat", models.FloatField(blank=True, null=True)),
                ("proposed_lon", models.FloatField(blank=True, null=True)),
                (
                    "proposed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Proposed date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("counter", "Counter-proposed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="gifting.ad",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Request",
                "verbose_name_plural": "Ad Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdRequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Message")),
                (
                    "status_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("counter", "Counter-proposed"),
                        ],
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "counter_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("my_place", "My place — come pick up / visit me"),
                            ("your_place", "Your place — I will bring it / visit you"),
                            ("custom", "Somewhere else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("counter_location", models.CharField(blank=True, max_length=255)),
                ("counter_lat", models.FloatField(blank=True, null=True)),
                ("counter_lon", models.FloatField(blank=True, null=True)),
                ("counter_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="gifting.adrequest",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_request_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Request Message",
                "verbose_name_plural": "Ad Request Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
