# Generated by Django 4.2.30 on 2026-05-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunitySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="What can visitors learn here?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_skills",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Skill",
                "verbose_name_plural": "Community Skills",
                "ordering": ["skill__name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SkillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("my_place", "My place — come visit me"),
                            ("your_place", "Your place — I will visit you"),
                            ("custom", "Somewhere else"),
                        ],
                        default="your_place",
                        max_length=20,
                        verbose_name="Meeting location",
                    ),
                ),
                (
                    "proposed_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Custom location"
                    ),
                ),
                ("proposed_lat", models.FloatField(blank=True, null=True)),
                ("proposed_lon", models.FloatField(blank=True, null=True)),
                (
                    "proposed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Proposed date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("counter", "Counter-proposed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="Response message"),
                ),
                (
                    "counter_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("my_place", "My place — come visit me"),
                            ("your_place", "Your place — I will visit you"),
                            ("custom", "Somewhere else"),
                        ],
                        max_length=20,
                        verbose_name="Counter location",
                    ),
                ),
                ("counter_location", models.CharField(blank=True, max_length=255)),
                ("counter_lat", models.FloatField(blank=True, null=True)),
                ("counter_lon", models.FloatField(blank=True, null=True)),
                (
                    "counter_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Counter date"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="skills.communityskill",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Request",
                "verbose_name_plural": "Skill Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="How did you learn this? What can you offer?",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, verbose_name="Available to teach / share"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Skill",
                "verbose_name_plural": "User Skills",
                "ordering": ["skill__name"],
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.CreateModel(
            name="SkillWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="What do you want to learn, or what do you need?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_wishes",
                        to="communities.community",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_wishes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Wish",
                "verbose_name_plural": "Skill Wishes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillRequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Message")),
                (
                    "status_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("counter", "Counter-proposed"),
                        ],
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "counter_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("my_place", "My place — come visit me"),
                            ("your_place", "Your place — I will visit you"),
                            ("custom", "Somewhere else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("counter_location", models.CharField(blank=True, max_length=255)),
                ("counter_lat", models.FloatField(blank=True, null=True)),
                ("counter_lon", models.FloatField(blank=True, null=True)),
                ("counter_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="skills.skillrequest",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_request_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Request Message",
                "verbose_name_plural": "Skill Request Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="user_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="skills.userskill",
            ),
        ),
        migrations.AddField(
            model_name="communityskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_skills",
                to="skills.skill",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communityskill",
            unique_together={("community", "skill")},
        ),
    ]
