# Generated by Django 4.2.30 on 2026-05-20 12:42

from django.db import migrations


def load_skills(apps, schema_editor):
    from skills.management.commands.load_curated_skills import SKILLS
    SkillTaxonomy = apps.get_model("skills", "SkillTaxonomy")
    for slug, en, de, es, fr in SKILLS:
        SkillTaxonomy.objects.update_or_create(
            slug=slug,
            defaults={"names": {"en": en, "de": de, "es": es, "fr": fr}},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_skills, migrations.RunPython.noop),
    ]
