# Generated by Django 4.2.30 on 2026-05-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_skillwish_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillrequest",
            name="wish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer_requests",
                to="skills.skillwish",
            ),
        ),
    ]
