# Generated by Django 4.2.30 on 2026-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_skillwish"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillrequest",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("my_place", "My place — come visit me"),
                    ("your_place", "Your place — I will visit you"),
                    ("custom", "Somewhere else"),
                ],
                default="your_place",
                max_length=20,
                verbose_name="Meeting location",
            ),
        ),
        migrations.AlterField(
            model_name="skillrequest",
            name="proposed_location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Custom location"
            ),
        ),
    ]
