# Generated by Django 4.2.30 on 2026-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_add_location_type_to_skillrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillrequest",
            name="counter_date",
            field=models.DateField(blank=True, null=True, verbose_name="Counter date"),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="counter_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="counter_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="counter_location_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("my_place", "My place — come visit me"),
                    ("your_place", "Your place — I will visit you"),
                    ("custom", "Somewhere else"),
                ],
                max_length=20,
                verbose_name="Counter location",
            ),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="counter_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="proposed_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="proposed_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="response_message",
            field=models.TextField(blank=True, verbose_name="Response message"),
        ),
        migrations.AddField(
            model_name="skillrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("counter", "Counter-proposed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
