# Generated by Django 4.2.30 on 2026-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tag",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
